{% set name = "dicto" %}
{% set version = "0.0.20" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 82557817b4c14d74497d98a99916249685c1a770fc35ff556ebebd2d2b5fad3a

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - dicto

about:
  home: https://github.com/cgarciae/dicto
  license: MIT
  license_family: MIT
  license_file: LICENSE 
  summary: A module that allows to read properties from yaml, and json and create a dicto object that behaves like a dictionary

extra:
  recipe-maintainers:
    - davidnet
